<<<<<<<< HEAD:course_discovery/apps/ietf_language_tags/migrations/0004_auto_20210119_0650.py
# Generated by Django 2.2.16 on 2021-01-19 06:50
========
# Generated by Django 2.2.14 on 2020-08-04 14:01
>>>>>>>> 1401e39e9d882120a410fe1bb61d21318c018a11:course_discovery/apps/ietf_language_tags/migrations/0004_auto_20200804_1401.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietf_language_tags', '0003_auto_20200506_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagetagtranslation',
            name='name_t',
            field=models.CharField(max_length=255, verbose_name='Name for translation'),
        ),
    ]
