# Generated by Django 4.2.20 on 2025-09-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_historicalpartner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpartner',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Disable Partner'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Disable Partner'),
        ),
    ]
