# Generated by Django 2.2.24 on 2023-11-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0269_depr_program_card_image_url_and_add_exec_ed_cert_type'),
        ('course_metadata', '0262_auto_20230621_1144'),
    ]

    operations = [
    ]
