# Generated by Django 2.2.16 on 2024-05-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0270_auto_20231024_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='course_difficulty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Difficulty'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Format'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_industry_certified_training',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CourseIndustry Certified Training'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_job_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Job Roles'),
        ),
        migrations.AddField(
            model_name='courserun',
            name='course_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Owner'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_difficulty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Difficulty'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Format'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_industry_certified_training',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CourseIndustry Certified Training'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_job_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Job Roles'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Owner'),
        ),
    ]
