# Generated by Django 2.2.16 on 2024-09-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0272_auto_20240830_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courserun',
            name='course_language',
        ),
        migrations.RemoveField(
            model_name='historicalcourserun',
            name='course_language',
        ),
    ]
