# Generated by Django 2.2.24 on 2024-10-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0274_auto_20240911_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
