# Generated by Django 3.2.20 on 2023-10-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0321_add_verified_only_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courserun',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcourserun',
            name='card_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
