# Generated by Django 4.2.20 on 2025-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0351_bulkoperationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='invite_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='invite_only',
            field=models.BooleanField(default=False),
        ),
    ]
