# Generated by Django 4.2.20 on 2025-08-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0352_courserun_invite_only_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
