# Generated by Django 4.2.20 on 2025-08-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0354_person_designation_person_marketing_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='marketing_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
