# Generated by Django 4.2.20 on 2025-09-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0356_courserun_is_marketing_price_hidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='yt_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube Video URL'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='yt_video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube Video URL'),
        ),
    ]
