# Generated by Django 4.2.20 on 2025-09-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0357_courserun_yt_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserun',
            name='course_duration_override',
            field=models.PositiveIntegerField(blank=True, help_text='This field contains override course duration value.', null=True, verbose_name='Course Duration Override'),
        ),
        migrations.AddField(
            model_name='historicalcourserun',
            name='course_duration_override',
            field=models.PositiveIntegerField(blank=True, help_text='This field contains override course duration value.', null=True, verbose_name='Course Duration Override'),
        ),
    ]
