# Generated by Django 4.2.20 on 2025-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0359_courserun_course_difficulty_courserun_course_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='program',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
