# Generated by Django 5.2.6 on 2026-04-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0356_add_course_editor_update_bulk_operation'),
        ('course_metadata', '0360_historicalprogram_featured_program_featured'),
    ]

    operations = [
    ]
